-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
--
-- 记录当前输入法
-- Current_input_method = vim.fn.system("/usr/local/bin/macism")
--
-- -- 切换到英文输入法
-- function Switch_to_English_input_method()
--   Current_input_method = vim.fn.system("/usr/local/bin/macism")
--   if Current_input_method ~= "com.apple.keylayout.ABC\n" then
--     vim.fn.system("/usr/local/bin/macism com.apple.keylayout.ABC")
--   end
-- end
--
-- -- 设置输入法
-- function Set_input_method()
--   if Current_input_method ~= "com.apple.keylayout.ABC\n" then
--     vim.fn.system("/usr/local/bin/macism " .. string.gsub(Current_input_method, "\n", ""))
--   end
-- end
--
-- -- 进入 normal 模式时切换为英文输入法
-- vim.cmd([[
-- augroup input_method
--   autocmd!
--   autocmd InsertEnter * :lua Set_input_method()
--   autocmd InsertLeave * :lua Switch_to_English_input_method()
-- augroup END
-- ]])
