return {
  -- {
  --   "milanglacier/minuet-ai.nvim",
  --   config = function()
  --     require("minuet").setup({
  --       -- provider = "openai_compatible",
  --       -- context_window = 16000,
  --       -- provider_options = {
  --       --   openai_compatible = {
  --       --     name = "Openrouter",
  --       --     end_point = "https://aihubmix.com/v1/chat/completions",
  --       --     model = "claude-3-7-sonnet-20250219",
  --       --     api_key = "AIHUBMIX_API_KEY",
  --       --     optional = { max_tokens = 128, top_p = 0.9 },
  --       --   },
  --       -- },
  --
  --       provider = "openai_fim_compatible",
  --       n_completions = 1,
  --       context_window = 512,
  --       provider_options = {
  --         openai_fim_compatible = {
  --           api_key = "TERM",
  --           name = "Ollama",
  --           end_point = "http://localhost:11434/v1/completions",
  --           model = "qwen2.5-coder:7b",
  --           optional = {
  --             max_tokens = 56,
  --             top_p = 0.9,
  --           },
  --         },
  --       },
  --
  --       virtualtext = {
  --         auto_trigger_ft = { "*" },
  --         keymap = {
  --           accept = "<A-A>",
  --           accept_line = "<A-a>",
  --           accept_n_lines = "<A-z>",
  --           prev = "<A-[>",
  --           next = "<A-]>",
  --           dismiss = "<A-e>",
  --         },
  --       },
  --
  --       cmp = {
  --         enable_auto_complete = false,
  --       },
  --       blink = {
  --         enable_auto_complete = false,
  --       },
  --     })
  --   end,
  -- },
  --
  -- { "nvim-lua/plenary.nvim" },
}
