return {
  -- {
  --   "milanglacier/minuet-ai.nvim",
  --   config = function()
  --     require("minuet").setup({
  --       provider = "openai_fim_compatible",
  --
  --       n_completions = 1,
  --       context_window = 512,
  --       provider_options = {
  --         openai_fim_compatible = {
  --           api_key = "TERM",
  --           name = "Ollama",
  --           end_point = "http://localhost:11434/v1/completions",
  --           model = "qwen2.5-coder:7b",
  --           optional = {
  --             max_tokens = 56,
  --             top_p = 0.9,
  --           },
  --         },
  --       },
  --       virtualtext = {
  --         auto_trigger_ft = { "*" },
  --         -- auto_trigger_ft = { "javascript", "typescript", "javascriptreact", "typescriptreact" },
  --         keymap = {
  --           accept = "<Tab>",
  --           accept_line = "<D-a>",
  --           accept_n_lines = "<A-z>",
  --           prev = "<A-[>",
  --           next = "<A-]>",
  --           dismiss = "<A-e>",
  --         },
  --       },
  --
  --       cmp = {
  --
  --         enable_auto_complete = false,
  --       },
  --       blink = {
  --         enable_auto_complete = false,
  --       },
  --     })
  --   end,
  -- },
  --
  -- { "nvim-lua/plenary.nvim" },
}
