return {

  -- {
  --   -- "atiladefreitas/dooing",
  --   dir = "~/.config/nvim/clone/dooing",
  --   config = function()
  --     require("dooing").setup({
  --       -- your custom config here (optional)
  --       save_path = "/Users/zhoushitie/vaults/personal/.todos.json",
  --       -- save_path = "/Users/zhoushitie/.config/nvim/todos.json",
  --
  --       -- Timestamp settings
  --       timestamp = {
  --         enabled = true, -- Show relative timestamps (e.g., @5m ago, @2h ago)
  --       },
  --
  --       -- Window settings
  --       window = {
  --         width = 100, -- Width of the floating window
  --         height = 15, -- Height of the floating window
  --         border = "rounded", -- Border style
  --         position = "center", -- Window position: 'right', 'left', 'top', 'bottom', 'center',
  --         -- 'top-right', 'top-left', 'bottom-right', 'bottom-left'
  --         padding = {
  --           top = 1,
  --           bottom = 1,
  --           left = 2,
  --           right = 2,
  --         },
  --       },
  --
  --       done_sort_by_completed_time = true,
  --
  --       -- To-do formatting
  --       formatting = {
  --         pending = {
  --           icon = "○",
  --           format = { "icon", "notes_icon", "text", "due_date", "ect" },
  --         },
  --         in_progress = {
  --           icon = "◐",
  --           format = { "icon", "text", "due_date", "ect" },
  --         },
  --         done = {
  --           icon = "✓",
  --           format = { "icon", "notes_icon", "text", "due_date", "ect" },
  --         },
  --       },
  --
  --       quick_keys = true, -- Quick keys window
  --
  --       notes = {
  --         icon = "📓",
  --       },
  --
  --       scratchpad = {
  --         syntax_highlight = "markdown",
  --       },
  --
  --       -- Keymaps
  --       keymaps = {
  --         toggle_window = "<leader>td",
  --         new_todo = "i",
  --         toggle_todo = "x",
  --         delete_todo = "d",
  --         delete_completed = "D",
  --         close_window = "q",
  --         undo_delete = "u",
  --         add_due_date = "H",
  --         remove_due_date = "r",
  --         toggle_help = "?",
  --         toggle_tags = "t",
  --         toggle_priority = "<Space>",
  --         clear_filter = "c",
  --         edit_todo = "e",
  --         edit_tag = "e",
  --         edit_priorities = "p",
  --         delete_tag = "d",
  --         search_todos = "/",
  --         add_time_estimation = "T",
  --         remove_time_estimation = "R",
  --         import_todos = "I",
  --         export_todos = "E",
  --         remove_duplicates = "<leader>D",
  --         open_todo_scratchpad = "<leader>p",
  --         refresh_todos = "F",
  --       },
  --
  --       calendar = {
  --         language = "en",
  --         icon = "",
  --         keymaps = {
  --           previous_day = "h",
  --           next_day = "l",
  --           previous_week = "k",
  --           next_week = "j",
  --           previous_month = "H",
  --           next_month = "L",
  --           select_day = "<CR>",
  --           close_calendar = "q",
  --         },
  --       },
  --
  --       -- Priority settings
  --       priorities = {
  --         {
  --           name = "urgent",
  --           weight = 8,
  --         },
  --         {
  --           name = "important",
  --           weight = 4,
  --         },
  --         {
  --           name = "trivial",
  --           weight = 2,
  --         },
  --         {
  --           name = "future",
  --           weight = -1,
  --         },
  --       },
  --       priority_groups = {
  --         high = {
  --           members = { "urgent" },
  --           color = nil, -- 红色
  --           hl_group = "DiagnosticError",
  --         },
  --         medium = {
  --           members = { "important" },
  --           color = nil, -- 橙色
  --           hl_group = "DiagnosticWarn",
  --         },
  --         trivial = {
  --           members = { "trivial" },
  --           color = nil, -- 蓝色
  --           hl_group = "DiagnosticInfo",
  --         },
  --         low = {
  --           members = { "future" },
  --           color = "#89CFF0",
  --         },
  --       },
  --       hour_score_value = 1 / 8,
  --     })
  --   end,
  -- },

  -- {
  --   "lfilho/note2cal.nvim",
  --   config = function()
  --     require("note2cal").setup({
  --       debug = false, -- if true, prints a debug message an return early (won't schedule events)
  --       calendar_name = "zhouatie@gmail.com", -- the name of the calendar as it appear on Calendar.app
  --       highlights = {
  --         at_symbol = "WarningMsg", -- the highlight group for the "@" symbol
  --         at_text = "Number", -- the highlight group for the date-time part
  --       },
  --       keymaps = {
  --         normal = "<Leader>se", -- mnemonic: Schedule Event
  --         visual = "<Leader>se", -- mnemonic: Schedule Event
  --       },
  --     })
  --   end,
  --   ft = "markdown",
  -- },

  -- 画图
  -- {
  --   "jbyuki/venn.nvim",
  -- },
}
