return {
  -- {
  --   "NickvanDyke/opencode.nvim",
  --   dependencies = {
  --     -- Recommended for `ask()` and `select()`.
  --     -- Required for `snacks` provider.
  --     ---@module 'snacks' <- Loads `snacks.nvim` types for configuration intellisense.
  --     { "folke/snacks.nvim", opts = { input = {}, picker = {}, terminal = {} } },
  --   },
  --   config = function()
  --     ---@type opencode.Opts
  --     vim.g.opencode_opts = {
  --       -- Your configuration, if any — see `lua/opencode/config.lua`, or "goto definition" on the type or field.
  --     }
  --
  --     -- Required for `opts.events.reload`.
  --     vim.o.autoread = true
  --
  --     -- Recommended/example keymaps.
  --     -- <C-a>: 询问 opencode（发送当前文件/选区作为上下文）
  --     vim.keymap.set({ "n", "x" }, "<C-q>", function()
  --       require("opencode").ask("@this: ", { submit = true })
  --     end, { desc = "Ask opencode…" })
  --     -- <C-x>: 执行 opencode 动作（选择操作）
  --     vim.keymap.set({ "n", "x" }, "<C-x>", function()
  --       require("opencode").select()
  --     end, { desc = "Execute opencode action…" })
  --     -- <C-.>: 切换 opencode 窗口
  --     vim.keymap.set({ "n", "t" }, "<C-.>", function()
  --       require("opencode").toggle()
  --     end, { desc = "Toggle opencode" })
  --
  --     -- go: 将选区/范围添加到 opencode 会话
  --     vim.keymap.set({ "n", "x" }, "go", function()
  --       return require("opencode").operator("@this ")
  --     end, { desc = "Add range to opencode", expr = true })
  --     -- goo: 将当前行添加到 opencode 会话
  --     vim.keymap.set("n", "goo", function()
  --       return require("opencode").operator("@this ") .. "_"
  --     end, { desc = "Add line to opencode", expr = true })
  --
  --     -- <S-C-u>: 向上滚动 opencode 窗口
  --     vim.keymap.set("n", "<S-C-u>", function()
  --       require("opencode").command("session.half.page.up")
  --     end, { desc = "Scroll opencode up" })
  --     -- <S-C-d>: 向下滚动 opencode 窗口
  --     vim.keymap.set("n", "<S-C-d>", function()
  --       require("opencode").command("session.half.page.down")
  --     end, { desc = "Scroll opencode down" })
  --
  --     -- 恢复 <C-a> 和 <C-x> 的原始功能（数字增减）
  --     -- +: 光标下数字增加
  --     vim.keymap.set("n", "+", "<C-a>", { desc = "Increment under cursor", noremap = true })
  --     -- -: 光标下数字减少
  --     vim.keymap.set("n", "-", "<C-x>", { desc = "Decrement under cursor", noremap = true })
  --   end,
  -- },
}
